# Elasticsearch monitoring stack for docker swarm


version: '3.8'


configs:
  logstash_config:
    external: true
  kibana_config:
    external: true
  heartbeat_config:
    external: true


volumes:
  certs:
    driver: local
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  logstash_pipeline:
    driver: local


networks:
  private:
  public:
  traefik-public:
    external: true


services:
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.labels.elasticsearch == 1   
      resources:
        limits:
          cpus: '3'
          memory: 3000M
    environment:
      - discovery.type=single-node
      - ELASTIC_CLUSTER_NAME=${ELASTIC_CLUSTER_NAME}
      - ELASTIC_NETWORK_HOST=${ELASTIC_NETWORK_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    networks:
      - private
      - public
    ports:
      - ${ELASTIC_PORT}:9200
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    deploy:
      placement:
        constraints:
          - node.labels.kibana == 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.kibana-http.rule=Host(`kibana.${DOMAIN?Variable not set}`)
        - traefik.http.routers.kibana-http.entrypoints=http
        - traefik.http.routers.kibana-http.middlewares=https-redirect
        - traefik.http.routers.kibana-https.rule=Host(`kibana.${DOMAIN?Variable not set}`)
        - traefik.http.routers.kibana-https.entrypoints=https
        - traefik.http.routers.kibana-https.tls=true
        - traefik.http.routers.kibana-https.tls.certresolver=le
        - traefik.http.services.kibana.loadbalancer.server.port=5601    
    environment:
      - SERVERNAME=kibana
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${ELASTIC_SSL_CERTIFICATEAUTHORITIES}
      - KIBANA_HOST=${KIBANA_HOST}
      - KIBANA_PUBLIC_URL=https://kibana.${DOMAIN}
      - KIBANA_SECURITY_ENCRYPTION_KEY=${KIBANA_SECURITY_ENCRYPTION_KEY}
      - KIBANA_REPORTING_ENCRYPTION_KEY=${KIBANA_REPORTING_ENCRYPTION_KEY}
      - KIBANA_SAVED_OBJECTS_ENCRYPTION_KEY=${KIBANA_SAVED_OBJECTS_ENCRYPTION_KEY}
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    networks:
      - private
      - traefik-public
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibana_data:/usr/share/kibana/data
        
  logstash:
    configs:
      - source: logstash_config
        target: /usr/share/logstash/pipeline/logstash.conf
    deploy:
      mode: global
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    networks:
      - private
    ports:
      - "12201:12201/udp"
    volumes:
      - certs:/usr/share/logstash/config/certs
      - logstash_pipeline:/usr/share/logstash/pipeline/

