# Elasticsearch monitoring stack for docker swarm


version: '3.8'


configs:
  logstash_config:
    external: true
  # metricbeat_config:
  #   external: true

volumes:
  esdata:
    driver: local
  logstash-pipeline:
    driver: local

networks:
  private:
  public:
  traefik-public:
    external: true

services:

  # metricbeat:
  #   image: docker.elastic.co/beats/metricbeat:8.2.3
  #   user: root
  #   hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
  #   configs:
  #     - source: metricbeat-config
  #       target: /usr/share/metricbeat/metricbeat.yml
  #   command:
  #     - -e
  #     - --strict.perms=false
  #     - --system.hostfs=/hostfs
  #   volumes:
  #     - type: bind
  #       source: /
  #       target: /hostfs
  #       read_only: true
  #     - type: bind
  #       source: /sys/fs/cgroup
  #       target: /hostfs/sys/fs/cgroup
  #       read_only: true
  #     - type: bind
  #       source: /proc
  #       target: /hostfs/proc
  #       read_only: true
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #       read_only: true
  #   deploy:
  #     mode: global

  elasticsearch:
    image: elasticsearch:8.2.3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    networks:
      - private
      - public
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.2.3
    networks:
      - private
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.swarmprom-kibana-http.rule=Host(`kibana.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-kibana-http.entrypoints=http
        - traefik.http.routers.swarmprom-kibana-http.middlewares=https-redirect
        - traefik.http.routers.swarmprom-kibana-https.rule=Host(`kibana.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-kibana-https.entrypoints=https
        - traefik.http.routers.swarmprom-kibana-https.tls=true
        - traefik.http.routers.swarmprom-kibana-https.tls.certresolver=le
        - traefik.http.services.swarmprom-kibana.loadbalancer.server.port=5601
        - traefik.http.middlewares.swarmprom-kibana-auth.basicauth.users=${ADMIN_USER?Variable not set}:${HASHED_PASSWORD?Variable not set}
        - traefik.http.routers.swarmprom-kibana-https.middlewares=swarmprom-kibana-auth    
        
  logstash:
    image: logstash:8.2.3
    ports:
      - "12201:12201/udp"
    networks:
      - private
    deploy:
      mode: global
    configs:
      - source: logstash_config
        target: /usr/share/logstash/pipeline/logstash.conf
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/

