# Kibana config file
server.host: "${KIBANA_HOST}"
server.publicBaseUrl: "${KIBANA_PUBLIC_URL}"
server.shutdownTimeout: "5s"
elasticsearch.hosts: "${ELASTIC_HOSTS}"
monitoring.ui.container.elasticsearch.enabled: true
xpack.security.encryptionKey: "${KIBANA_SECURITY_ENCRYPTION_KEY}"
xpack.reporting.encryptionKey: "${KIBANA_REPORTING_ENCRYPTION_KEY}"
xpack.encryptedSavedObjects.encryptionKey: "${KIBANA_SAVED_OBJECTS_ENCRYPTION_KEY}"
xpack.reporting.kibanaServer.hostname: localhost
xpack.reporting.roles.enabled: false